In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns
from scipy import stats 
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import accuracy_score

# Loading source datasets

In [2]:

df=pd.read_csv("train_go05W65.csv")
test=pd.read_csv("test_VkM91FT.csv")



In [3]:
df.head(10)

Customer_ID  Gender  Age  Vintage  Is_Active City_Category  \
0    CC264719    Male   41       14          0            C1   
1    CC209679  Female   47       14          1            C1   
2    CC319633  Female   59       14          0            C2   
3    CC231413  Female   32       16          0            C1   
4    CC259633    Male   30       15          0            C2   
5    CC384429  Female   28       12          0            C1   
6    CC233048    Male   30       17          0            C1   
7    CC370586    Male   44       16          1            C2   
8    CC358694    Male   47       44          0            C2   
9    CC316464    Male   26       12          0            C2   

  Customer_Category     Product_Holding_B1 Product_Holding_B2  
0                S3                ['P16']             ['P8']  
1                S2         ['P13', 'P20']             ['P3']  
2                S2                ['P11']            ['P00']  
3                S2          ['P8', 'P13']             ['P6']  
4                S3  ['P16', 'P17', 'P21']      ['P8', 'P12']  
5                S2                ['P17']            ['P16']  
6                S2         ['P16', 'P17']             ['P8']  
7                S2         ['P16', 'P21']      ['P1', 'P12']  
8                S3         ['P13', 'P20']            ['P12']  
9                S3         ['P13', 'P21']             ['P9']

In [4]:
#Exploring shapes of source datasets
df.shape


(37748, 9)

In [5]:
test.shape

(20327, 8)

# Data cleansing: 

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37748 entries, 0 to 37747
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Customer_ID         37748 non-null  object
 1   Gender              37748 non-null  object
 2   Age                 37748 non-null  int64 
 3   Vintage             37748 non-null  int64 
 4   Is_Active           37748 non-null  int64 
 5   City_Category       37748 non-null  object
 6   Customer_Category   37748 non-null  object
 7   Product_Holding_B1  37748 non-null  object
 8   Product_Holding_B2  37748 non-null  object
dtypes: int64(3), object(6)
memory usage: 2.6+ MB


In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20327 entries, 0 to 20326
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Customer_ID         20327 non-null  object
 1   Gender              20327 non-null  object
 2   Age                 20327 non-null  int64 
 3   Vintage             20327 non-null  int64 
 4   Is_Active           20327 non-null  int64 
 5   City_Category       20327 non-null  object
 6   Customer_Category   20327 non-null  object
 7   Product_Holding_B1  20327 non-null  object
dtypes: int64(3), object(5)
memory usage: 1.2+ MB


In [8]:
df.isnull().sum()#checking whether dataset has null values and getting count of null values if any

Customer_ID           0
Gender                0
Age                   0
Vintage               0
Is_Active             0
City_Category         0
Customer_Category     0
Product_Holding_B1    0
Product_Holding_B2    0
dtype: int64

# no null values found

In [9]:
for x in df['Product_Holding_B1']:
    x=x.replace("'", "")
    print(x)

[P16]
[P13, P20]
[P11]
[P8, P13]
[P16, P17, P21]
[P17]
[P16, P17]
[P16, P21]
[P13, P20]
[P13, P21]
[P16]
[P16, P17]
[P12, P13, P21]
[P13]
[P17]
[P13, P21]
[P20]
[P13]
[P13]
[P13]
[P13]
[P13]
[P16, P17, P21]
[P16, P17]
[P10, P16]
[P16]
[P13, P21]
[P17, P19]
[P13]
[P13]
[P17]
[P2]
[P8, P16]
[P11]
[P12, P13, P19]
[P13]
[P13, P17, P21]
[P8, P13, P20, P21]
[P00]
[P13]
[P13, P17]
[P13, P21]
[P17]
[P12, P13]
[P16, P21]
[P12, P13]
[P16]
[P16, P17]
[P18]
[P12, P13]
[P13, P19]
[P13]
[P17]
[P8, P13]
[P21]
[P16]
[P17]
[P16]
[P21]
[P15, P17, P21]
[P00]
[P13, P20]
[P21]
[P11]
[P17]
[P13, P17]
[P12, P13, P17]
[P13]
[P13]
[P13, P17, P20]
[P11]
[P13]
[P10, P16]
[P16]
[P16, P17]
[P13]
[P16, P21]
[P15, P16]
[P13]
[P13]
[P11]
[P12, P13]
[P12, P13, P15]
[P17]
[P13]
[P13, P19]
[P8, P13]
[P00]
[P6, P13]
[P13, P21]
[P13]
[P11]
[P13]
[P17]
[P12, P13, P21]
[P10, P12, P15, P16]
[P13, P21]
[P21]
[P13, P17]
[P12, P13, P17]
[P13]
[P13]
[P17]
[P13]
[P21]
[P16]
[P12, P13]
[P13]
[P13]
[P16]
[P13, P20, P21]
[P8, P12, P

[P8, P13]
[P8, P10, P12, P16, P17]
[P16]
[P8, P16]
[P12, P16]
[P8, P13]
[P13]
[P8, P11]
[P13]
[P8, P16]
[P13, P21]
[P16, P21]
[P13, P17]
[P16]
[P12, P16]
[P12, P13, P21]
[P8, P13]
[P17]
[P16, P21]
[P13]
[P13]
[P8, P16]
[P8, P13]
[P16]
[P16]
[P9, P13]
[P00]
[P8]
[P13]
[P2]
[P13, P17, P20]
[P13, P20]
[P13]
[P13]
[P8, P13]
[P8, P16]
[P13]
[P8, P16]
[P13]
[P13]
[P16]
[P16]
[P17]
[P16]
[P8, P16, P17]
[P12, P13]
[P12, P16]
[P17]
[P12, P16, P17, P20, P21]
[P17]
[P13]
[P13]
[P12, P13, P17, P19]
[P8, P13]
[P13]
[P17]
[P12, P16, P21]
[P8, P13]
[P13, P21]
[P16, P21]
[P8, P13]
[P16, P21]
[P8, P12, P16]
[P17, P19]
[P21]
[P12, P13, P21]
[P16, P17]
[P13]
[P00]
[P16, P17]
[P17]
[P17]
[P17, P19]
[P12, P13]
[P16]
[P12, P17]
[P13]
[P12, P16, P20]
[P13, P17]
[P13, P19]
[P13]
[P12, P13, P18, P20]
[P16]
[P8, P13, P20]
[P17]
[P13]
[P17]
[P16, P21]
[P16, P21]
[P13, P17, P21]
[P17]
[P8, P13, P21]
[P16]
[P13]
[P13]
[P10, P13]
[P16]
[P13, P15, P21]
[P00]
[P13]
[P13, P17, P20]
[P13]
[P12, P16]
[P16]
[P20, P21]
[P

[P13]
[P13]
[P10, P13]
[P11]
[P17]
[P13]
[P15, P20]
[P13]
[P13]
[P12, P13, P17]
[P13]
[P10, P12, P13, P20]
[P5, P13]
[P13]
[P16, P17]
[P19, P20]
[P12, P13, P20, P21]
[P12, P13]
[P13, P20]
[P13]
[P13]
[P8, P13]
[P13]
[P13, P19]
[P00]
[P13]
[P13]
[P8, P16, P17]
[P17, P20]
[P16]
[P13, P17]
[P15, P16]
[P12, P16, P17, P21]
[P17, P20, P21]
[P11]
[P3, P13]
[P2]
[P13, P17]
[P16, P18]
[P13, P17]
[P8]
[P16]
[P16]
[P13]
[P13]
[P12, P13]
[P17]
[P13]
[P13]
[P17]
[P17]
[P12, P16, P20, P21]
[P12, P13, P21]
[P13, P17, P20]
[P13]
[P12, P16]
[P8, P16]
[P8, P13]
[P16]
[P13]
[P13]
[P11]
[P16, P17]
[P13]
[P2]
[P13, P19, P20]
[P10, P13, P21]
[P16]
[P13, P17]
[P2]
[P13]
[P16, P20, P21]
[P16]
[P12, P16]
[P16]
[P16, P17]
[P13, P21]
[P16]
[P13]
[P8, P13]
[P16]
[P13]
[P16]
[P13, P19]
[P13, P19]
[P13]
[P18]
[P3, P13]
[P16]
[P13]
[P13, P17]
[P8, P12, P13]
[P13, P15, P20]
[P12, P17]
[P16]
[P16]
[P16]
[P13]
[P13]
[P13]
[P8, P16]
[P16]
[P12, P13, P21]
[P17]
[P17]
[P12, P13, P17, P21]
[P13, P15]
[P13]
[P3, P13]
[P13]


[P16, P21]
[P13]
[P12, P13, P17, P20]
[P00]
[P13]
[P12, P16]
[P13]
[P13]
[P17]
[P11]
[P12, P13, P17, P19, P20]
[P12, P13]
[P8, P16]
[P11]
[P13]
[P16, P17]
[P12, P13, P19, P21]
[P17]
[P13]
[P20]
[P17]
[P13]
[P16, P17]
[P12, P16]
[P8, P12, P13]
[P13]
[P17]
[P13]
[P12, P16, P17]
[P2]
[P20, P21]
[P16]
[P13, P21]
[P16]
[P11]
[P21]
[P10, P13, P20, P21]
[P16]
[P10, P12, P16, P17, P19, P20, P21]
[P17, P21]
[P13]
[P8, P13]
[P13]
[P10, P13, P20]
[P00]
[P13, P17, P21]
[P16]
[P16, P21]
[P13, P19]
[P13]
[P10, P16]
[P12, P13, P15, P17]
[P13]
[P10, P16]
[P8, P13]
[P16]
[P16]
[P13]
[P17]
[P16]
[P11]
[P13, P17, P20]
[P13]
[P12, P16]
[P12, P16]
[P13, P21]
[P21]
[P13]
[P20]
[P12, P16]
[P13]
[P8, P16]
[P16]
[P8, P10, P16]
[P16]
[P13]
[P16, P21]
[P12, P13, P15, P17, P20]
[P17]
[P8, P16]
[P12, P16, P21]
[P13]
[P8, P13]
[P00]
[P13]
[P13]
[P13, P21]
[P10, P12, P13]
[P12, P16, P21]
[P11]
[P12, P16]
[P2]
[P16]
[P16]
[P21]
[P8, P13]
[P8, P16]
[P2]
[P16, P21]
[P12, P16]
[P12, P16]
[P8, P13]
[P13]
[P16, P17, P21]


[P12, P16, P21]
[P13]
[P17]
[P20]
[P13, P19]
[P13]
[P13]
[P13]
[P16]
[P13]
[P13, P19]
[P13, P21]
[P8, P13]
[P16]
[P11]
[P16, P18]
[P12, P16]
[P13, P17]
[P13, P20]
[P13]
[P16]
[P17]
[P12, P16]
[P17]
[P12, P16]
[P13]
[P13]
[P16, P20]
[P13, P17, P20]
[P13]
[P13]
[P13]
[P12, P13]
[P12, P16]
[P17]
[P16, P17]
[P10, P12, P16, P20]
[P12, P13, P21]
[P16]
[P13, P20, P21]
[P9, P13]
[P16, P21]
[P13, P20, P21]
[P13]
[P8, P10, P13, P21]
[P9, P13, P19, P20]
[P12, P16, P17, P20, P21]
[P8, P16]
[P17, P20]
[P13, P20]
[P13]
[P13, P20]
[P16]
[P13]
[P13, P21]
[P13, P21]
[P13]
[P9, P12, P17]
[P13]
[P13]
[P11]
[P20, P21]
[P00]
[P10, P12, P13]
[P13]
[P10, P16]
[P16, P21]
[P12, P13]
[P16, P17, P20]
[P12, P16]
[P21]
[P16]
[P13, P17]
[P13]
[P11, P12, P21]
[P12, P13]
[P16, P21]
[P12, P13, P21]
[P9, P12, P13, P20]
[P13, P21]
[P12, P13, P17]
[P13]
[P16]
[P16]
[P10, P12, P13, P19, P21]
[P16, P17]
[P13]
[P18, P21]
[P11]
[P17, P20]
[P13]
[P13, P15]
[P13]
[P13]
[P13, P15]
[P11]
[P17, P20]
[P12, P13, P21]
[P13, P21]
[P1

[P13, P17]
[P13, P21]
[P13, P21]
[P16]
[P12, P13, P17, P21]
[P21]
[P16]
[P16]
[P2]
[P10, P16]
[P13, P19]
[P13, P19]
[P13]
[P10, P12, P13]
[P12, P16, P19]
[P13, P17]
[P2]
[P13]
[P13]
[P16]
[P12, P16, P21]
[P10, P12, P13]
[P13, P19]
[P9, P13]
[P16]
[P16, P19]
[P13]
[P16]
[P13]
[P20]
[P13, P17]
[P10, P13]
[P17]
[P21]
[P12, P13]
[P16, P20]
[P17, P20]
[P13]
[P13, P17]
[P13]
[P12, P16, P20, P21]
[P00]
[P8, P13]
[P00]
[P13, P20]
[P13, P21]
[P16, P19]
[P13]
[P13]
[P19]
[P16]
[P13]
[P19]
[P16, P21]
[P13, P15, P17, P21]
[P16]
[P7, P13]
[P13, P20]
[P11]
[P16, P21]
[P16]
[P10, P12]
[P10, P13]
[P12, P13, P17]
[P13]
[P16, P17]
[P8, P16]
[P00]
[P8, P16]
[P11]
[P13]
[P17, P19]
[P16]
[P12, P13, P17]
[P13]
[P12, P13, P20]
[P21]
[P16]
[P16, P17, P20, P21]
[P13]
[P13, P21]
[P13, P17, P21]
[P13]
[P13]
[P16]
[P16, P17]
[P7, P13]
[P13]
[P12, P16, P17]
[P16]
[P17]
[P13, P20]
[P16]
[P14, P15, P21]
[P13, P19, P20]
[P11]
[P10, P12, P16, P17, P21]
[P20]
[P12, P16]
[P16, P21]
[P21]
[P13, P21]
[P16, P21]
[P16]
[P13

[P12, P16, P21]
[P00]
[P00]
[P2]
[P13, P21]
[P13, P17]
[P13]
[P13]
[P5, P21]
[P7, P13]
[P13]
[P13, P21]
[P00]
[P17]
[P16, P21]
[P13]
[P13]
[P13, P17]
[P11]
[P13]
[P13]
[P13]
[P8, P13]
[P13]
[P00]
[P12, P16]
[P13, P17, P21]
[P16]
[P17]
[P17, P19]
[P13, P17, P21]
[P00]
[P10, P12, P17, P21]
[P16]
[P12, P16]
[P12, P13, P17]
[P6]
[P7, P13]
[P13, P17]
[P13, P17]
[P16, P17]
[P13]
[P17, P20, P21]
[P17]
[P13]
[P16, P17]
[P13]
[P13, P17]
[P13]
[P8]
[P16, P21]
[P10, P12, P16, P21]
[P17]
[P10, P12, P13, P21]
[P12, P13]
[P6, P13]
[P21]
[P00]
[P17]
[P13]
[P13]
[P17]
[P2]
[P2]
[P16, P21]
[P18, P21]
[P13, P21]
[P13, P17]
[P12, P16]
[P17]
[P16]
[P11]
[P13]
[P13, P21]
[P16, P17, P20]
[P17]
[P13, P15, P17, P20]
[P16, P21]
[P13]
[P16, P19, P20]
[P17, P20, P21]
[P8, P13]
[P12, P13]
[P6, P13]
[P9, P16]
[P11]
[P16]
[P16]
[P4, P8]
[P16]
[P17]
[P8]
[P16, P17, P20]
[P4, P12]
[P13]
[P12, P16, P17]
[P00]
[P13, P17]
[P13, P19, P20]
[P12, P13, P20]
[P13]
[P12, P13, P17]
[P16]
[P00]
[P19]
[P00]
[P13, P18]
[P16, P21]

[P00]
[P20]
[P11]
[P8, P13]
[P11]
[P13]
[P12, P16, P20]
[P17, P20, P21]
[P11]
[P16]
[P17]
[P8, P13]
[P16, P17]
[P21]
[P12, P16, P17]
[P13, P19]
[P15, P16, P20, P21]
[P20]
[P13]
[P16, P17]
[P20]
[P13, P19]
[P17, P19]
[P12, P21]
[P13, P20]
[P16]
[P11]
[P16, P17]
[P17]
[P12, P13, P17]
[P13]
[P16]
[P13]
[P12, P13, P21]
[P13, P20, P21]
[P16]
[P8, P13]
[P16]
[P13]
[P12, P16]
[P16]
[P16]
[P16, P20]
[P12, P13, P17]
[P21]
[P16]
[P17]
[P13, P21]
[P8, P12, P13, P21]
[P12, P16]
[P12, P16]
[P16]
[P00]
[P00]
[P16]
[P12, P20, P21]
[P10, P12, P13, P21]
[P16]
[P12, P16]
[P12, P21]
[P16]
[P10, P13]
[P10, P12, P13, P17]
[P12, P16]
[P11]
[P13]
[P8, P13]
[P16, P21]
[P12, P16, P21]
[P12, P13, P21]
[P16]
[P20]
[P19]
[P13]
[P16, P21]
[P00]
[P13]
[P13]
[P17]
[P11]
[P16, P17]
[P8]
[P21]
[P2]
[P16, P21]
[P19, P20]
[P16]
[P13, P21]
[P16]
[P12, P16, P17]
[P00]
[P13]
[P13]
[P10, P16]
[P21]
[P13, P17, P20]
[P17, P19]
[P18]
[P13]
[P11]
[P16]
[P12, P16]
[P12, P16, P21]
[P13, P21]
[P12, P16]
[P13]
[P13]
[P11, P12]
[P21

[P17]
[P12, P21]
[P13]
[P13, P17]
[P16]
[P16, P20]
[P2]
[P12, P13]
[P16]
[P13]
[P20]
[P13]
[P13, P20]
[P16]
[P2]
[P2]
[P11]
[P13]
[P17, P20, P21]
[P8, P13]
[P16]
[P00]
[P12, P13, P17]
[P13]
[P16]
[P13]
[P12, P13, P17, P20]
[P8, P12, P16]
[P00]
[P9, P13, P20, P21]
[P17]
[P13, P20]
[P13, P19]
[P13]
[P12, P13]
[P16, P21]
[P13]
[P10, P12, P13]
[P16, P19]
[P12, P13]
[P16]
[P13]
[P21]
[P17]
[P11]
[P20]
[P12, P13, P17]
[P13, P19]
[P11]
[P13, P17, P20]
[P16, P21]
[P11, P19]
[P16]
[P16]
[P16]
[P13]
[P13]
[P16]
[P12, P17]
[P13, P17, P21]
[P12, P16, P17]
[P13, P17]
[P13]
[P2]
[P13]
[P13]
[P13]
[P16]
[P9, P13, P20]
[P20]
[P13, P21]
[P12, P13, P17]
[P16]
[P17]
[P12, P21]
[P13, P20]
[P10, P12, P13, P17, P19]
[P9, P10, P13, P21]
[P8, P16, P21]
[P16]
[P16, P20]
[P21]
[P16]
[P13]
[P12, P16, P17]
[P12, P19]
[P12, P13, P17, P21]
[P16, P21]
[P12, P13, P21]
[P13]
[P11]
[P16]
[P7, P13]
[P13]
[P13]
[P17]
[P17]
[P17]
[P11]
[P10, P16]
[P13, P17]
[P13]
[P16]
[P00]
[P13, P21]
[P16]
[P13, P17]
[P13, P17]
[P10, P1

[P13]
[P13, P21]
[P13, P19]
[P9, P12, P13]
[P7, P16]
[P13]
[P11]
[P13, P19]
[P16]
[P13, P19]
[P13]
[P16, P20]
[P17, P20, P21]
[P16, P19]
[P8, P16]
[P13, P15, P17]
[P13]
[P10, P12, P16, P17]
[P12, P16, P19]
[P13]
[P12, P13, P15, P17]
[P13, P19]
[P10, P13]
[P13, P17, P21]
[P16]
[P13, P15, P17, P20]
[P13]
[P11]
[P2]
[P13, P19]
[P16, P21]
[P13, P17]
[P16, P21]
[P13]
[P17]
[P16]
[P13]
[P12, P16]
[P13, P21]
[P17]
[P13, P21]
[P11]
[P13, P15, P17, P20]
[P11]
[P13, P21]
[P16]
[P13, P19]
[P16, P17, P19, P20]
[P6, P16]
[P7, P8]
[P12, P13]
[P17, P19]
[P00]
[P13]
[P8, P16]
[P10, P12, P16]
[P13]
[P8, P16]
[P13, P21]
[P16]
[P00]
[P13, P17, P20]
[P12, P15, P16, P17, P20, P21]
[P16]
[P13]
[P13]
[P17]
[P13]
[P13]
[P8, P12, P13, P17]
[P12, P16, P21]
[P8, P13]
[P12, P16]
[P19, P20]
[P17]
[P16]
[P8, P13]
[P16]
[P8]
[P11]
[P8, P11, P21]
[P20]
[P19]
[P12, P13, P21]
[P16, P20]
[P18, P21]
[P13]
[P8, P16]
[P16]
[P13, P21]
[P13]
[P11]
[P16]
[P12, P16]
[P12, P13, P17]
[P8, P13]
[P16, P17]
[P16, P17, P18]
[P12, P1

[P16, P21]
[P16]
[P17]
[P13]
[P20, P21]
[P8, P13]
[P21]
[P12, P13]
[P16, P17]
[P12, P16]
[P7, P13]
[P13, P20, P21]
[P12, P16]
[P2]
[P13]
[P13]
[P21]
[P16]
[P13, P21]
[P16]
[P18, P20, P21]
[P17, P21]
[P16, P17]
[P13, P17]
[P16]
[P2]
[P16, P17, P18, P20, P21]
[P8, P13]
[P13]
[P11]
[P11]
[P13, P19]
[P12, P13, P21]
[P12, P13]
[P16]
[P00]
[P9, P13]
[P13]
[P19]
[P16]
[P8, P13]
[P2]
[P13]
[P17]
[P11, P12]
[P16]
[P12, P13, P21]
[P20]
[P11]
[P12, P16, P21]
[P00]
[P16]
[P16]
[P16]
[P13]
[P13, P20]
[P11]
[P13]
[P16]
[P13, P21]
[P3]
[P13]
[P9, P16]
[P16]
[P00]
[P16]
[P16, P19]
[P16, P17]
[P13, P21]
[P13, P17, P21]
[P12, P16]
[P16, P21]
[P13, P17]
[P16, P20]
[P17]
[P8, P16]
[P8, P12, P13, P17]
[P8, P9, P13]
[P16]
[P17]
[P8, P16]
[P10, P13]
[P12, P16]
[P11]
[P17, P20]
[P13, P19, P21]
[P16]
[P16]
[P11]
[P16, P21]
[P13]
[P16]
[P13]
[P16, P17]
[P8, P13]
[P16]
[P13]
[P13]
[P8, P13]
[P21]
[P12, P16]
[P2]
[P17, P21]
[P16]
[P16]
[P11]
[P16, P17]
[P13]
[P17]
[P16, P21]
[P13, P21]
[P13, P19]
[P00]
[P17, P21]

[P12, P16]
[P17]
[P7, P13]
[P16]
[P10, P11, P19]
[P21]
[P16, P19]
[P13, P17]
[P10, P12, P13, P17, P20, P21]
[P16]
[P16, P20]
[P16, P17]
[P17, P21]
[P17, P19, P20]
[P13]
[P16]
[P12, P13]
[P8, P11]
[P13]
[P20]
[P8, P13]
[P13, P21]
[P11]
[P16]
[P13, P21]
[P12, P21]
[P17]
[P11]
[P12, P13, P21]
[P11]
[P10, P12, P13, P21]
[P16, P19]
[P12, P13]
[P12, P13, P21]
[P17]
[P13]
[P13, P17]
[P16]
[P12, P16]
[P17, P21]
[P17]
[P16, P20]
[P13, P19]
[P16]
[P16]
[P6]
[P8, P13]
[P17]
[P13]
[P13, P20]
[P13, P17]
[P13]
[P17]
[P13]
[P12, P13]
[P11]
[P00]
[P12, P13, P21]
[P13, P17, P21]
[P13]
[P00]
[P16]
[P12, P13, P21]
[P8, P12, P16]
[P12, P13, P21]
[P8]
[P7, P8, P10, P16]
[P21]
[P13, P21]
[P8, P9, P13]
[P17, P20]
[P16, P17]
[P13, P17]
[P00]
[P12, P16]
[P13]
[P13, P17]
[P10, P16]
[P16, P17, P19, P21]
[P13]
[P17]
[P13]
[P13, P21]
[P12, P13]
[P12, P13]
[P8, P13]
[P19]
[P16, P21]
[P13, P17]
[P8, P10, P16]
[P2]
[P17]
[P12, P13, P17]
[P2]
[P8, P10, P12, P16]
[P12, P13, P21]
[P17]
[P17]
[P16]
[P16]
[P13, P21]
[P17]

[P16]
[P7, P16]
[P16, P17]
[P16, P20]
[P16]
[P15]
[P13]
[P13]
[P13]
[P16, P21]
[P12, P13, P21]
[P11]
[P13]
[P16]
[P16, P17, P19]
[P12, P13]
[P17]
[P13, P17, P20]
[P13]
[P16, P17]
[P13]
[P13]
[P17]
[P17]
[P13]
[P8, P21]
[P13]
[P13, P17, P21]
[P13]
[P12, P21]
[P12, P13, P17]
[P20]
[P2]
[P11]
[P17]
[P13]
[P12, P13]
[P12, P13, P21]
[P8, P13]
[P16, P17]
[P9, P10, P11]
[P17, P19]
[P21]
[P12, P16, P17, P21]
[P12, P13, P17]
[P13, P19]
[P11]
[P21]
[P14, P16, P17, P21]
[P16, P20]
[P13]
[P13]
[P13]
[P16]
[P12, P13, P21]
[P10, P13]
[P16]
[P7, P16]
[P13]
[P20, P21]
[P12, P13, P21]
[P9, P16]
[P16]
[P13]
[P12, P13, P19]
[P3, P13]
[P16, P20, P21]
[P16]
[P12, P16, P21]
[P8, P16]
[P12, P13, P21]
[P13]
[P16]
[P13, P19, P20]
[P12, P13]
[P12, P13, P21]
[P13]
[P13, P17, P20]
[P21]
[P16, P17]
[P13]
[P16]
[P13]
[P12, P13]
[P13, P21]
[P20]
[P12, P13]
[P13]
[P16]
[P13, P19]
[P10, P12, P16]
[P13]
[P12, P13, P21]
[P8, P13]
[P16]
[P13]
[P7, P16]
[P16]
[P13]
[P12, P13, P17]
[P11]
[P7, P8]
[P2]
[P16]
[P13]
[P13, P21

[P2]
[P13, P17, P21]
[P13, P17]
[P13]
[P13]
[P12, P13]
[P12, P16, P21]
[P16]
[P13]
[P13, P21]
[P8]
[P17]
[P13, P21]
[P8, P11]
[P13]
[P13]
[P10, P16]
[P12, P13, P17, P19]
[P12, P13]
[P19]
[P13]
[P16]
[P16, P21]
[P13]
[P16]
[P12, P16]
[P13]
[P8, P12, P13]
[P13, P20]
[P10, P12, P13, P20]
[P13, P18, P20]
[P16]
[P13, P21]
[P15]
[P15, P16]
[P13]
[P12, P16, P21]
[P16, P21]
[P13]
[P12, P16, P17]
[P8, P13]
[P17]
[P16, P17]
[P17]
[P13]
[P11]
[P18]
[P16]
[P13, P19]
[P13]
[P13, P19]
[P21]
[P17]
[P16, P20]
[P12, P13]
[P16, P17]
[P17]
[P00]
[P17]
[P13, P21]
[P13]
[P13]
[P8, P13]
[P2]
[P9, P10, P13]
[P13, P21]
[P11]
[P13, P20]
[P17]
[P21]
[P12, P13]
[P12, P21]
[P8, P13]
[P13]
[P13]
[P12, P13, P21]
[P13]
[P12, P13]
[P16]
[P13, P17]
[P20]
[P13, P15, P17]
[P12, P21]
[P12, P13]
[P13]
[P11]
[P16]
[P13]
[P18]
[P8, P13]
[P16, P19]
[P13]
[P12, P13, P21]
[P7, P16]
[P13]
[P16]
[P17]
[P13, P17]
[P17]
[P16, P21]
[P16]
[P11]
[P13]
[P16]
[P16, P17]
[P9, P13]
[P10, P13]
[P16]
[P13, P21]
[P11]
[P13]
[P13]
[P10, P13]

[P13]
[P13]
[P13, P21]
[P16]
[P13]
[P17]
[P16]
[P11]
[P12, P13]
[P12, P13, P17]
[P13, P17]
[P12, P13]
[P12, P13, P19]
[P12, P21]
[P17, P20, P21]
[P16, P21]
[P13, P17, P21]
[P13]
[P9, P13]
[P16, P20]
[P17, P20]
[P17]
[P13, P21]
[P17]
[P13, P18]
[P13, P21]
[P16]
[P16]
[P8, P11]
[P16]
[P13, P17]
[P16, P17]
[P11]
[P13]
[P16]
[P13]
[P12, P16]
[P12, P13]
[P00]
[P9, P10, P13, P17]
[P16]
[P13]
[P13]
[P00]
[P13, P15]
[P21]
[P12, P13]
[P13, P19]
[P13, P21]
[P2]
[P8, P12, P13, P21]
[P13]
[P8, P11]
[P11]
[P13]
[P13]
[P13]
[P2]
[P20]
[P10, P12, P16, P19, P21]
[P16, P21]
[P16]
[P12, P13]
[P00]
[P16, P17, P21]
[P16, P19]
[P16]
[P16, P21]
[P16]
[P12, P13, P20, P21]
[P13]
[P16, P21]
[P17]
[P12, P13, P20]
[P8, P11]
[P13, P17, P20, P21]
[P17]
[P13, P17, P21]
[P13]
[P4, P13]
[P17]
[P13]
[P15, P17, P19]
[P16]
[P16]
[P00]
[P12, P13]
[P16]
[P9, P12, P13, P19]
[P16, P17, P21]
[P17]
[P8, P12, P13]
[P16]
[P17]
[P12, P13, P21]
[P16, P20]
[P13]
[P16]
[P16]
[P17]
[P8, P13]
[P16, P19]
[P17]
[P16, P21]
[P16]
[P13]
[

[P11]
[P16]
[P12, P13]
[P2]
[P17]
[P13]
[P10, P12, P16]
[P11]
[P13]
[P12, P13, P21]
[P15]
[P17, P19]
[P12, P13, P17, P21]
[P8, P12, P13, P17]
[P10, P13]
[P19]
[P8, P13]
[P11]
[P12, P13]
[P13]
[P12, P16, P21]
[P11]
[P17]
[P13, P20]
[P17, P19]
[P15, P16, P17]
[P12, P13]
[P13, P17]
[P8]
[P15, P17, P21]
[P20]
[P12, P16, P17, P19]
[P00]
[P13, P17]
[P13]
[P16, P21]
[P17]
[P17]
[P13]
[P16]
[P8, P16]
[P12, P13, P21]
[P8, P16]
[P16, P17]
[P13, P17]
[P16]
[P17]
[P13]
[P00]
[P8, P16]
[P16, P21]
[P16]
[P9, P13]
[P16]
[P13]
[P17]
[P13]
[P8, P16, P21]
[P16]
[P8, P12]
[P13]
[P16, P17, P21]
[P13]
[P16]
[P16]
[P13]
[P00]
[P13, P17]
[P8, P16]
[P17]
[P9, P13]
[P16]
[P13]
[P13]
[P16, P21]
[P13]
[P16, P17, P20, P21]
[P16]
[P12, P13, P17]
[P8, P16]
[P13]
[P13, P21]
[P12, P16, P17, P19, P20, P21]
[P00]
[P13, P17]
[P12, P16]
[P13]
[P13]
[P13]
[P13]
[P17]
[P16]
[P13, P21]
[P8, P16]
[P13]
[P16, P21]
[P20]
[P13]
[P13, P17]
[P13, P17, P20, P21]
[P12, P16]
[P12, P16, P17, P19, P20]
[P13]
[P8, P12, P13, P17]
[P12, 

[P13]
[P16]
[P10, P12, P16]
[P11, P12]
[P11]
[P21]
[P12, P13, P20]
[P20]
[P13]
[P11]
[P11]
[P17]
[P8, P12, P13]
[P13]
[P13, P17]
[P10, P12, P17, P20, P21]
[P13]
[P13]
[P12, P13, P17, P21]
[P13]
[P17]
[P13, P20]
[P13]
[P15, P17]
[P17, P19, P20]
[P8, P13]
[P16, P17, P21]
[P13, P17, P21]
[P13, P21]
[P12, P13, P17]
[P13]
[P13, P17]
[P10, P13]
[P8, P20]
[P13, P21]
[P2]
[P12, P13]
[P13]
[P16]
[P12, P16, P21]
[P19]
[P13, P21]
[P16, P21]
[P16]
[P12, P16]
[P16]
[P16]
[P13]
[P12, P13, P19]
[P13]
[P13, P20]
[P8, P13]
[P11]
[P16, P21]
[P12, P16, P20, P21]
[P17]
[P16, P17]
[P13]
[P16]
[P12, P13]
[P20]
[P12, P16]
[P13, P17]
[P12, P13, P21]
[P19]
[P13]
[P13, P17]
[P13]
[P13]
[P11]
[P12, P13]
[P13, P21]
[P8, P10, P13]
[P12, P13, P19, P21]
[P13]
[P13]
[P13]
[P13, P17]
[P13, P21]
[P12, P13]
[P16]
[P13]
[P16]
[P12, P16]
[P10, P12, P13, P17, P21]
[P8]
[P13, P14]
[P10, P13]
[P16, P17]
[P11]
[P13]
[P12, P13, P21]
[P16, P21]
[P11]
[P11, P12]
[P12, P16, P17]
[P12, P13]
[P16]
[P13]
[P13]
[P12]
[P13]
[P17, P19]

[P13]
[P13]
[P13]
[P13]
[P12, P13, P17]
[P19]
[P13]
[P13]
[P13]
[P13]
[P11, P17]
[P17]
[P13, P17]
[P8, P16]
[P8, P16]
[P12, P13]
[P13, P18]
[P10, P12, P16, P17, P21]
[P16]
[P00]
[P13]
[P17, P19]
[P13, P17, P18]
[P20]
[P16]
[P13, P19]
[P16]
[P16, P21]
[P13]
[P13]
[P13]
[P13]
[P16]
[P16, P21]
[P16, P19]
[P8, P13]
[P13, P20]
[P2]
[P17]
[P7, P8, P11]
[P16]
[P11]
[P12, P16]
[P17]
[P13, P17]
[P13]
[P16]
[P11, P12]
[P16]
[P20, P21]
[P2]
[P12, P16, P17]
[P12, P16]
[P12, P16, P21]
[P13]
[P16]
[P12, P13]
[P8, P12, P13, P17]
[P12, P16]
[P13, P19]
[P13]
[P13]
[P12, P13]
[P21]
[P13, P17]
[P16, P21]
[P20, P21]
[P13]
[P13]
[P13]
[P13]
[P17, P20, P21]
[P13]
[P13]
[P17]
[P16]
[P10, P12, P13, P21]
[P13]
[P15, P17, P19]
[P16, P20]
[P8, P16]
[P13]
[P10, P16]
[P13]
[P18]
[P9, P13]
[P17]
[P16, P21]
[P20]
[P16, P21]
[P9, P12, P16, P19, P21]
[P13, P21]
[P13]
[P13]
[P13, P17]
[P12, P13, P20, P21]
[P16]
[P16, P17]
[P16, P21]
[P16]
[P13, P17, P20, P21]
[P13]
[P17]
[P8, P13]
[P16, P17]
[P17, P20]
[P16]
[P17]
[P13

[P8]
[P16, P17]
[P16, P21]
[P17, P20, P21]
[P13]
[P13]
[P8, P12, P13, P20]
[P20]
[P13, P15, P21]
[P13]
[P20, P21]
[P12]
[P16, P21]
[P12, P13, P21]
[P13]
[P13]
[P12, P13, P20]
[P13]
[P9, P13]
[P21]
[P13]
[P00]
[P2]
[P10, P16]
[P17]
[P12, P13, P20, P21]
[P12, P13, P21]
[P7, P16]
[P11]
[P16]
[P17]
[P10, P16]
[P15, P17, P19, P20, P21]
[P16, P21]
[P12, P13, P19]
[P19, P21]
[P13, P20]
[P13]
[P13]
[P20]
[P16, P17]
[P8, P13]
[P17]
[P16]
[P8, P12, P17]
[P20]
[P11]
[P18]
[P13]
[P16]
[P12, P13, P21]
[P8, P10, P12, P21]
[P16, P19]
[P13]
[P13]
[P13]
[P13]
[P13]
[P13, P21]
[P13, P17]
[P11]
[P13]
[P17]
[P16]
[P12, P16, P17]
[P12, P13, P21]
[P12, P16, P20, P21]
[P8, P20]
[P13, P21]
[P16]
[P9, P16]
[P19]
[P13]
[P12, P13]
[P16, P19, P21]
[P13]
[P16]
[P17]
[P11]
[P7, P13]
[P13, P19]
[P20]
[P16]
[P7, P13]
[P13]
[P12, P16]
[P17]
[P9, P13]
[P8, P16]
[P16]
[P16]
[P16, P21]
[P8, P13]
[P12, P13]
[P10, P16]
[P13]
[P16, P21]
[P8, P12, P13, P17]
[P00]
[P11]
[P13, P21]
[P17, P20]
[P17]
[P13]
[P16, P21]
[P10, P16]


[P8, P13]
[P7, P13]
[P12, P16, P17]
[P12, P13, P17]
[P13, P17]
[P17, P20]
[P16, P21]
[P00]
[P10, P13, P17]
[P12, P21]
[P13]
[P13]
[P17]
[P12, P13]
[P13]
[P17]
[P16]
[P12, P13]
[P16, P17, P21]
[P13]
[P13]
[P13, P17]
[P17]
[P16, P17]
[P20]
[P19, P21]
[P13, P20]
[P13]
[P17]
[P17]
[P13]
[P11]
[P16]
[P17]
[P12, P16]
[P17]
[P13]
[P13]
[P13]
[P12, P16]
[P8, P13, P21]
[P16]
[P8, P13, P19]
[P3, P13]
[P00]
[P10, P13]
[P11]
[P16, P17]
[P13]
[P16, P21]
[P16]
[P20]
[P16]
[P12, P13, P17, P21]
[P8, P16]
[P12, P21]
[P13]
[P17]
[P13]
[P16, P21]
[P17, P19, P20, P21]
[P16, P17]
[P13]
[P13]
[P13, P17]
[P16, P21]
[P16, P19]
[P9, P13]
[P13, P19]
[P17]
[P13]
[P16, P17]
[P12, P13]
[P13, P17]
[P13, P17]
[P00]
[P13]
[P12, P16]
[P16, P21]
[P16, P21]
[P12, P13, P20]
[P9, P16, P20]
[P7, P16]
[P17]
[P20]
[P12, P13]
[P8, P13]
[P13]
[P10, P12, P13]
[P12, P16]
[P13]
[P11]
[P9, P10, P12, P13, P17, P20, P21]
[P13]
[P16]
[P13]
[P11]
[P11]
[P17]
[P16, P17]
[P16]
[P16]
[P12, P13, P19]
[P13, P20]
[P00]
[P16, P21]
[P12, P13,

[P7, P8, P11]
[P12, P16]
[P17]
[P16]
[P00]
[P13, P19]
[P12, P16, P20, P21]
[P8, P13]
[P16]
[P16, P21]
[P11]
[P21]
[P16]
[P13]
[P13, P15]
[P17]
[P17]
[P13, P17]
[P13]
[P20]
[P13]
[P8, P13]
[P13]
[P11]
[P13, P20, P21]
[P12, P13, P21]
[P6, P8]
[P10, P12, P13]
[P13]
[P17]
[P16, P21]
[P11]
[P12, P13, P17]
[P20]
[P13]
[P13]
[P12, P13, P17]
[P13]
[P16]
[P13]
[P16]
[P19]
[P21]
[P13]
[P12, P21]
[P12, P13, P17]
[P13]
[P13]
[P17]
[P12, P16]
[P9, P13]
[P13]
[P13]
[P13]
[P13]
[P13]
[P13]
[P17]
[P12, P13, P15, P17]
[P13]
[P11]
[P17]
[P4, P10, P16]
[P16, P17, P19, P21]
[P13, P14, P20]
[P16]
[P00]
[P3]
[P12, P18, P21]
[P12, P16, P21]
[P13, P17]
[P9, P10, P12, P15, P16, P20, P21]
[P21]
[P13]
[P16]
[P16]
[P21]
[P16]
[P16, P20]
[P13]
[P20]
[P12, P13]
[P6, P8, P13]
[P21]
[P16]
[P8, P13]
[P16, P21]
[P16]
[P11]
[P20]
[P13]
[P21]
[P12, P13]
[P13]
[P17]
[P13]
[P16, P21]
[P13, P21]
[P12, P21]
[P13]
[P13, P17]
[P13]
[P16, P17, P21]
[P16, P17, P21]
[P16, P17]
[P13, P17]
[P16, P17]
[P10, P12, P13, P17, P20, P21]


[P19]
[P16]
[P16]
[P2]
[P21]
[P9, P13]
[P16, P19]
[P13]
[P16]
[P16, P17, P20, P21]
[P5, P16]
[P13]
[P21]
[P16]
[P2]
[P00]
[P10, P16]
[P8, P16]
[P12, P13]
[P16, P21]
[P00]
[P16, P17]
[P13, P21]
[P9, P10, P16, P20, P21]
[P2]
[P9, P12, P13]
[P21]
[P12, P16]
[P13, P19]
[P8, P16, P17]
[P20, P21]
[P7, P13]
[P13, P17]
[P13]
[P8, P16]
[P13]
[P7, P13]
[P17]
[P13]
[P16, P17, P19, P20]
[P13]
[P13, P19]
[P13]
[P16, P21]
[P13]
[P13, P19]
[P13, P20]
[P13]
[P8, P15]
[P13]
[P13]
[P16]
[P8, P12, P13]
[P16]
[P13]
[P13, P19]
[P16, P21]
[P13]
[P17]
[P16, P21]
[P13]
[P20]
[P16, P21]
[P16, P17, P20]
[P13, P20, P21]
[P16, P20]
[P13, P17]
[P12, P21]
[P13, P14]
[P13]
[P8, P16]
[P12, P13]
[P15, P16]
[P13]
[P13, P15, P17, P20]
[P11]
[P17, P20]
[P16]
[P16, P21]
[P13]
[P13]
[P13]
[P13]
[P16, P21]
[P13]
[P12, P16]
[P11]
[P13, P19]
[P11]
[P13]
[P16, P20]
[P17]
[P12, P13]
[P11]
[P11]
[P13, P17]
[P13]
[P11]
[P16, P17, P19]
[P13]
[P12, P16, P17, P19, P21]
[P10, P12, P13, P15, P17]
[P16]
[P16, P17]
[P16, P21]
[P13]
[P18

[P21]
[P7, P16]
[P19, P20]
[P16]
[P15]
[P6, P13]
[P13]
[P12, P13, P17, P20]
[P16, P19]
[P17]
[P16]
[P00]
[P8, P13]
[P16, P21]
[P16]
[P11, P12, P17, P21]
[P9, P13]
[P11]
[P17]
[P16, P21]
[P16]
[P17]
[P13]
[P13, P21]
[P13]
[P21]
[P13]
[P13]
[P13]
[P12, P13, P17]
[P8, P16]
[P8, P16, P17]
[P13]
[P10, P12, P13]
[P16, P17, P21]
[P8, P16]
[P15, P16, P20]
[P13]
[P13]
[P11]
[P19]
[P16]
[P8, P16]
[P16, P20]
[P12, P13, P21]
[P13, P17, P20]
[P9, P13]
[P20]
[P12, P21]
[P2]
[P13, P19]
[P20]
[P12, P20, P21]
[P19, P21]
[P13]
[P11]
[P16]
[P16]
[P16]
[P13]
[P10, P12, P13, P15]
[P16, P17]
[P13]
[P13]
[P16]
[P8, P12, P16]
[P10, P12, P16, P17]
[P16]
[P12, P13, P17]
[P16, P20]
[P17]
[P13]
[P16, P17]
[P13, P21]
[P17]
[P17]
[P9, P16, P19]
[P16, P21]
[P12, P13, P17]
[P16, P20]
[P13, P15, P21]
[P13]
[P12, P13]
[P13, P21]
[P11, P12]
[P13, P21]
[P16]
[P9, P12, P13, P17]
[P13]
[P13]
[P11]
[P16]
[P19]
[P2]
[P13]
[P11]
[P12, P13, P21]
[P8, P16]
[P00]
[P13]
[P16]
[P12, P13]
[P12, P16, P21]
[P6, P8]
[P12, P16]
[P2]
[P

In [10]:
for x in test['Product_Holding_B1']:
    x=x.replace("'", "")
    print(x)

[P12, P13]
[P12, P13]
[P20]
[P13, P21]
[P13]
[P13, P20]
[P17]
[P16, P20]
[P16]
[P10, P12, P16]
[P12, P13, P17, P19, P21]
[P17]
[P12, P16, P17]
[P8]
[P16]
[P16, P17]
[P12, P13, P17, P20]
[P8, P12, P16]
[P13]
[P13]
[P13]
[P13]
[P21]
[P16]
[P16]
[P8, P16]
[P13, P17]
[P13]
[P10, P12, P13]
[P13]
[P11]
[P16]
[P11]
[P17]
[P13]
[P17]
[P13, P19]
[P16, P17]
[P13, P17]
[P13, P17]
[P12, P16, P21]
[P16, P20]
[P21]
[P13]
[P13]
[P13]
[P15]
[P16]
[P17, P21]
[P16]
[P13]
[P9, P10, P12, P21]
[P17]
[P17]
[P16]
[P11]
[P13, P21]
[P13]
[P11, P12]
[P12, P17]
[P16]
[P13, P15, P17, P20, P21]
[P17]
[P16, P19]
[P12, P16]
[P16, P19]
[P19]
[P17]
[P13]
[P16]
[P20]
[P2]
[P13]
[P17, P20, P21]
[P16, P21]
[P2]
[P9, P13]
[P11]
[P21]
[P13, P17]
[P10, P16]
[P13]
[P17]
[P12, P17, P21]
[P00]
[P13]
[P8, P16]
[P16]
[P11, P12, P17, P20, P21]
[P8, P13]
[P13, P21]
[P00]
[P16]
[P00]
[P11]
[P16, P21]
[P17]
[P12, P20, P21]
[P21]
[P00]
[P12, P21]
[P13]
[P16]
[P00]
[P17]
[P11, P12, P21]
[P12, P16]
[P13]
[P20]
[P00]
[P13]
[P13]
[P13]
[

[P17]
[P12, P13]
[P13]
[P18, P20, P21]
[P2]
[P12, P16, P20, P21]
[P8, P16, P17]
[P16]
[P13]
[P11, P14]
[P13]
[P11, P12]
[P16]
[P12, P13, P20]
[P8, P16, P21]
[P21]
[P16]
[P16, P20, P21]
[P17, P20, P21]
[P13, P17]
[P16]
[P13]
[P8, P12, P13, P20]
[P13, P21]
[P11]
[P13]
[P17, P20]
[P2]
[P18, P19, P20]
[P12, P13]
[P12, P13]
[P13]
[P2]
[P13, P21]
[P12, P13, P21]
[P2]
[P7, P11]
[P13]
[P13]
[P12, P16]
[P16, P20]
[P17, P20, P21]
[P13, P20]
[P13, P17]
[P12, P16]
[P13]
[P13]
[P14, P15, P19]
[P17, P19]
[P8, P16]
[P12, P13, P21]
[P18]
[P16]
[P13, P20]
[P7, P13]
[P13]
[P10, P13]
[P13]
[P13, P20]
[P16, P17]
[P16, P20]
[P16, P21]
[P10, P12, P16]
[P13]
[P11]
[P13]
[P12, P13, P17]
[P2]
[P12, P16, P21]
[P13, P20]
[P9, P16]
[P13]
[P7, P16]
[P11]
[P20]
[P10]
[P13, P17, P20]
[P16, P20]
[P13, P21]
[P16]
[P16, P17]
[P8, P13, P20]
[P13]
[P13]
[P2]
[P16]
[P13]
[P8, P13, P21]
[P8, P13]
[P13]
[P13]
[P13, P21]
[P13]
[P13, P15, P21]
[P20]
[P16, P21]
[P16]
[P13, P20]
[P13]
[P13]
[P17]
[P12, P16, P17, P21]
[P13, P18,

[P13, P17]
[P13]
[P20]
[P16, P17]
[P8, P10, P16, P21]
[P13, P20]
[P13]
[P13]
[P13, P21]
[P17, P21]
[P10, P13]
[P13]
[P16]
[P17]
[P13, P17]
[P16]
[P13]
[P16, P20]
[P12, P13, P21]
[P11]
[P13]
[P16, P21]
[P16, P17]
[P13]
[P11]
[P2]
[P10, P12]
[P12, P13, P21]
[P13]
[P10, P12, P13, P17, P19, P21]
[P12, P13]
[P8, P13]
[P12, P13]
[P13, P17]
[P13, P21]
[P10, P12, P13]
[P10, P13]
[P13]
[P16]
[P13]
[P16]
[P13, P17]
[P00]
[P12, P16, P17, P21]
[P16]
[P17]
[P20]
[P12, P13]
[P12, P16]
[P7, P16]
[P12, P13, P19]
[P13, P15, P17, P21]
[P16, P21]
[P13, P21]
[P12, P13]
[P16, P17]
[P13, P17]
[P12, P13, P19]
[P13]
[P12, P16]
[P13, P21]
[P2]
[P13, P21]
[P13, P19, P21]
[P13, P20]
[P00]
[P16, P21]
[P16]
[P13]
[P15, P21]
[P8]
[P13, P17]
[P00]
[P8, P13]
[P16]
[P16, P21]
[P13]
[P15, P16, P17]
[P16, P19]
[P9, P13]
[P16, P17]
[P12, P13, P21]
[P8, P13]
[P8, P16]
[P13]
[P16, P21]
[P11]
[P13]
[P16]
[P12, P16]
[P16, P21]
[P10, P16]
[P16, P21]
[P13, P21]
[P17]
[P00]
[P11]
[P13]
[P16, P18, P20]
[P12, P13]
[P13, P17]
[P13

[P17]
[P12, P13, P21]
[P19]
[P8, P16]
[P13]
[P8, P13]
[P13, P19]
[P21]
[P16]
[P13]
[P12, P16]
[P12, P16, P17, P20]
[P16]
[P10, P12, P17]
[P12, P13, P21]
[P13, P15]
[P16, P21]
[P17]
[P17]
[P13]
[P19]
[P11]
[P13]
[P13]
[P17]
[P13, P17]
[P8, P12, P16]
[P8, P13, P20]
[P8, P12, P16]
[P17]
[P16]
[P12, P16]
[P16, P20]
[P2]
[P2]
[P16]
[P7, P16]
[P12, P13, P17]
[P13]
[P7, P13]
[P17]
[P13, P20]
[P16]
[P3, P21]
[P13, P21]
[P17]
[P12, P16]
[P00]
[P11]
[P16, P17, P19]
[P11]
[P20]
[P10, P12, P16]
[P13, P21]
[P17]
[P17]
[P13, P20]
[P16, P21]
[P11]
[P13, P19]
[P17]
[P16]
[P2]
[P16]
[P12, P16]
[P12, P16, P21]
[P13]
[P13]
[P8, P13]
[P17]
[P8]
[P10, P16]
[P13]
[P11]
[P13]
[P16]
[P21]
[P13]
[P13]
[P8, P13]
[P13, P21]
[P13, P21]
[P13, P17]
[P13, P17]
[P8, P12, P13]
[P19]
[P18]
[P16]
[P8, P13]
[P11]
[P16, P21]
[P16]
[P8, P13]
[P13]
[P13, P21]
[P16, P20]
[P16]
[P13]
[P17]
[P16, P20]
[P13]
[P16]
[P20]
[P17, P20]
[P11]
[P16, P17]
[P13, P20]
[P12, P13]
[P21]
[P13, P15]
[P13]
[P16]
[P13]
[P12, P13, P19]
[P13]
[P

[P13, P15]
[P16]
[P17]
[P16]
[P13]
[P21]
[P12, P13]
[P17]
[P11]
[P20]
[P13]
[P11]
[P11]
[P13]
[P13]
[P10, P13]
[P13, P20, P21]
[P13]
[P17]
[P13, P20]
[P2]
[P13]
[P13, P19]
[P12, P13, P20]
[P12, P13]
[P17, P19]
[P13, P20]
[P2]
[P16]
[P13]
[P12, P13, P20]
[P13, P19]
[P21]
[P13]
[P17]
[P00]
[P13, P17]
[P12, P16]
[P12, P13, P21]
[P10, P12, P13]
[P13]
[P13, P20]
[P18]
[P00]
[P11]
[P9, P13]
[P13]
[P13]
[P13]
[P12, P16]
[P7]
[P12, P13, P17, P20, P21]
[P16]
[P16, P21]
[P13, P17, P21]
[P16]
[P13]
[P17]
[P13, P20]
[P13, P20]
[P13]
[P13]
[P12, P16]
[P8, P10, P13, P21]
[P15]
[P13, P20, P21]
[P13]
[P21]
[P13, P20]
[P16, P21]
[P12, P13]
[P16]
[P7]
[P8, P16]
[P16]
[P17]
[P13, P21]
[P12, P13]
[P16, P19]
[P13]
[P10, P16]
[P11]
[P16, P17]
[P12, P13, P17]
[P8, P16]
[P16]
[P15, P16, P17]
[P8, P13]
[P20]
[P8, P13]
[P16]
[P13]
[P8, P12, P13]
[P7, P13]
[P13]
[P18]
[P13]
[P13]
[P8, P16]
[P12, P16, P17]
[P13]
[P13, P15, P20, P21]
[P12, P16]
[P13]
[P16, P17]
[P13]
[P13, P19]
[P13, P17]
[P16]
[P13, P20]
[P13]
[P

[P13, P20]
[P13]
[P16, P17]
[P13]
[P12, P13]
[P2]
[P20, P21]
[P2]
[P12, P16, P21]
[P8, P13]
[P13, P20]
[P16]
[P8, P16, P20]
[P13]
[P13]
[P16]
[P17, P20, P21]
[P16, P17, P20, P21]
[P16, P17, P20]
[P12, P16, P20, P21]
[P11, P12, P21]
[P7, P13]
[P9, P13]
[P13]
[P8, P12, P13]
[P13, P17]
[P12, P16, P21]
[P13]
[P13, P17, P20]
[P13, P21]
[P13]
[P13]
[P16, P17, P18, P19, P20]
[P13]
[P13]
[P16]
[P12, P13]
[P13, P20]
[P16]
[P13]
[P16]
[P13]
[P12, P13, P17, P20, P21]
[P8]
[P13, P19]
[P20]
[P13, P19]
[P13]
[P13]
[P13]
[P17]
[P10, P11, P12]
[P8, P13]
[P8]
[P15, P16]
[P13]
[P8, P10, P13, P20]
[P16, P21]
[P12, P13, P17]
[P2]
[P12, P16]
[P2]
[P16, P19]
[P16, P20]
[P16]
[P12, P16]
[P17]
[P13, P17]
[P7, P8, P12]
[P13]
[P17]
[P10, P16, P20, P21]
[P13]
[P16]
[P12, P16]
[P21]
[P21]
[P8, P13]
[P13, P17]
[P12, P16]
[P7, P13]
[P17, P20, P21]
[P10, P16]
[P16]
[P12, P16, P19]
[P8, P16]
[P8, P13]
[P16, P19]
[P12, P16]
[P12, P13, P17]
[P17]
[P17]
[P16]
[P11]
[P16]
[P12, P13]
[P16, P17]
[P8, P16]
[P13, P15, P21]
[

[P13]
[P12, P19]
[P13]
[P21]
[P12, P16, P17]
[P16]
[P16]
[P00]
[P12, P13, P18, P20, P21]
[P12, P13, P17]
[P13]
[P9, P13, P20]
[P13]
[P13]
[P11]
[P16]
[P00]
[P16]
[P16, P19]
[P13]
[P8, P13]
[P12, P13, P17]
[P12, P13]
[P20]
[P12, P13, P20]
[P13, P17]
[P12, P19, P20, P21]
[P20]
[P13]
[P13]
[P12, P16]
[P16]
[P16]
[P13]
[P13]
[P12, P16]
[P16, P20]
[P16, P17]
[P11]
[P13]
[P2]
[P13, P17]
[P13]
[P2]
[P15, P20, P21]
[P13]
[P16, P21]
[P13]
[P00]
[P16]
[P17]
[P16, P17, P21]
[P12, P16, P21]
[P13, P19]
[P15, P17, P21]
[P16, P21]
[P16, P17]
[P21]
[P12, P16, P17]
[P16]
[P12, P13, P21]
[P12, P13]
[P17]
[P12, P13]
[P00]
[P17]
[P16]
[P13]
[P11]
[P16, P21]
[P21]
[P13]
[P21]
[P11]
[P17]
[P13]
[P16]
[P16, P20]
[P12, P13]
[P16]
[P00]
[P13, P20]
[P13, P17]
[P16, P21]
[P17]
[P2]
[P16, P21]
[P16, P21]
[P13, P17]
[P13]
[P16, P17, P20]
[P16]
[P10, P16]
[P16]
[P11]
[P13, P20]
[P13]
[P13]
[P12, P13, P19]
[P8, P13]
[P11]
[P10, P13]
[P12, P13, P17]
[P16, P17]
[P17, P19]
[P16, P17]
[P12, P16]
[P12, P17]
[P12, P13, P1

[P12, P13]
[P13]
[P00]
[P16, P17]
[P10, P12, P16]
[P21]
[P13]
[P16]
[P16]
[P11]
[P16]
[P8, P16]
[P2]
[P17, P21]
[P16, P21]
[P13, P20]
[P11]
[P16]
[P8, P13]
[P17]
[P17]
[P12, P16, P18, P20]
[P16, P20]
[P8, P16]
[P00]
[P00]
[P12, P16]
[P13, P17]
[P16]
[P16]
[P13, P21]
[P13]
[P12, P13]
[P8, P9, P13]
[P12, P16, P21]
[P12, P13, P20]
[P12, P16, P21]
[P13]
[P8, P16]
[P12, P13]
[P10, P13, P18, P21]
[P13]
[P16]
[P20]
[P16, P21]
[P13, P19, P21]
[P13]
[P16]
[P13]
[P16, P21]
[P10, P12]
[P17, P20]
[P12, P20, P21]
[P13, P21]
[P21]
[P16, P21]
[P16]
[P8, P16]
[P16, P17, P19, P20, P21]
[P16, P21]
[P16, P17]
[P16]
[P16]
[P13]
[P13, P21]
[P20]
[P13, P17, P20, P21]
[P12, P16, P21]
[P16, P20]
[P12, P13, P21]
[P16]
[P13]
[P8, P16]
[P13]
[P12, P13, P17]
[P13, P21]
[P16, P20]
[P16]
[P16, P17]
[P13]
[P16]
[P9, P13]
[P12, P16]
[P16, P17, P21]
[P16]
[P16]
[P8, P12]
[P11]
[P17]
[P16]
[P13]
[P13]
[P16, P18, P21]
[P16]
[P11]
[P12, P13]
[P17]
[P16]
[P13]
[P13]
[P11]
[P13]
[P16]
[P12, P16]
[P8, P16]
[P19]
[P16, P21]


In [11]:
df['Product_Holding_B1']=[x.replace("'", "") for x in df['Product_Holding_B1']]

In [12]:
test['Product_Holding_B1']=[x.replace("'", "") for x in test['Product_Holding_B1']]

In [13]:
df['Product_Holding_B2']=[x.replace("'", "") for x in df['Product_Holding_B2']]

In [14]:
df

Customer_ID  Gender  Age  Vintage  Is_Active City_Category  \
0        CC264719    Male   41       14          0            C1   
1        CC209679  Female   47       14          1            C1   
2        CC319633  Female   59       14          0            C2   
3        CC231413  Female   32       16          0            C1   
4        CC259633    Male   30       15          0            C2   
...           ...     ...  ...      ...        ...           ...   
37743    CC314217    Male   28       24          1            C1   
37744    CC388747    Male   36       11          0            C2   
37745    CC318056    Male   44       26          1            C2   
37746    CC373551  Female   56       15          1            C1   
37747    CC269624    Male   29       13          0            C2   

      Customer_Category Product_Holding_B1 Product_Holding_B2  
0                    S3              [P16]               [P8]  
1                    S2         [P13, P20]               [P3]  
2                    S2              [P11]              [P00]  
3                    S2          [P8, P13]               [P6]  
4                    S3    [P16, P17, P21]          [P8, P12]  
...                 ...                ...                ...  
37743                S2              [P16]               [P9]  
37744                S2    [P16, P17, P21]          [P5, P12]  
37745                S2              [P14]              [P13]  
37746                S2         [P12, P13]               [P1]  
37747                S2         [P16, P17]          [P8, P12]  

[37748 rows x 9 columns]

In [15]:
df['Product_Holding_B1']=[x.replace("[", "") for x in df['Product_Holding_B1']]

In [16]:
test['Product_Holding_B1']=[x.replace("[", "") for x in test['Product_Holding_B1']]

In [17]:
df['Product_Holding_B1']=[x.replace("]", "") for x in df['Product_Holding_B1']]

In [18]:
test['Product_Holding_B1']=[x.replace("]", "") for x in test['Product_Holding_B1']]

In [19]:
df['Product_Holding_B1']

0                  P16
1             P13, P20
2                  P11
3              P8, P13
4        P16, P17, P21
             ...      
37743              P16
37744    P16, P17, P21
37745              P14
37746         P12, P13
37747         P16, P17
Name: Product_Holding_B1, Length: 37748, dtype: object

In [20]:
df['Product_Holding_B2']=[x.replace("[", "") for x in df['Product_Holding_B2']]

In [21]:
df['Product_Holding_B2']=[x.replace("]", "") for x in df['Product_Holding_B2']]

In [22]:
df['Product_Holding_B2']=[list(x.split(", ")) for x in df['Product_Holding_B2']]

In [23]:
df['Product_Holding_B1']=[list(x.split(", ")) for x in df['Product_Holding_B1']]

In [24]:
test['Product_Holding_B1']=[list(x.split(", ")) for x in test['Product_Holding_B1']]

In [25]:
df['Product_Holding_B1']

0                  [P16]
1             [P13, P20]
2                  [P11]
3              [P8, P13]
4        [P16, P17, P21]
              ...       
37743              [P16]
37744    [P16, P17, P21]
37745              [P14]
37746         [P12, P13]
37747         [P16, P17]
Name: Product_Holding_B1, Length: 37748, dtype: object

In [26]:
df['Product_Holding_B2']

0             [P8]
1             [P3]
2            [P00]
3             [P6]
4        [P8, P12]
           ...    
37743         [P9]
37744    [P5, P12]
37745        [P13]
37746         [P1]
37747    [P8, P12]
Name: Product_Holding_B2, Length: 37748, dtype: object

In [27]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer(sparse_output=True)

df1 = df.join(
            pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(df.pop('Product_Holding_B1')),
                index=df.index,
                columns=mlb.classes_).add_prefix('B1_'))


In [28]:


df1 = df1.join(
            pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(df1.pop('Product_Holding_B2')),
                index=df.index,
                columns=mlb.classes_).add_prefix('B2_'))

In [29]:
df1

Customer_ID  Gender  Age  Vintage  Is_Active City_Category  \
0        CC264719    Male   41       14          0            C1   
1        CC209679  Female   47       14          1            C1   
2        CC319633  Female   59       14          0            C2   
3        CC231413  Female   32       16          0            C1   
4        CC259633    Male   30       15          0            C2   
...           ...     ...  ...      ...        ...           ...   
37743    CC314217    Male   28       24          1            C1   
37744    CC388747    Male   36       11          0            C2   
37745    CC318056    Male   44       26          1            C2   
37746    CC373551  Female   56       15          1            C1   
37747    CC269624    Male   29       13          0            C2   

      Customer_Category  B1_P00  B1_P1  B1_P10  ...  B2_P18  B2_P2  B2_P20  \
0                    S3       0      0       0  ...       0      0       0   
1                    S2       0      0       0  ...       0      0       0   
2                    S2       0      0       0  ...       0      0       0   
3                    S2       0      0       0  ...       0      0       0   
4                    S3       0      0       0  ...       0      0       0   
...                 ...     ...    ...     ...  ...     ...    ...     ...   
37743                S2       0      0       0  ...       0      0       0   
37744                S2       0      0       0  ...       0      0       0   
37745                S2       0      0       0  ...       0      0       0   
37746                S2       0      0       0  ...       0      0       0   
37747                S2       0      0       0  ...       0      0       0   

       B2_P3  B2_P4  B2_P5  B2_P6  B2_P7  B2_P8  B2_P9  
0          0      0      0      0      0      1      0  
1          1      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      1      0      0      0  
4          0      0      0      0      0      1      0  
...      ...    ...    ...    ...    ...    ...    ...  
37743      0      0      0      0      0      0      1  
37744      0      0      1      0      0      0      0  
37745      0      0      0      0      0      0      0  
37746      0      0      0      0      0      0      0  
37747      0      0      0      0      0      1      0  

[37748 rows x 49 columns]

In [30]:
df1.columns

Index(['Customer_ID', 'Gender', 'Age', 'Vintage', 'Is_Active', 'City_Category',
       'Customer_Category', 'B1_P00', 'B1_P1', 'B1_P10', 'B1_P11', 'B1_P12',
       'B1_P13', 'B1_P14', 'B1_P15', 'B1_P16', 'B1_P17', 'B1_P18', 'B1_P19',
       'B1_P2', 'B1_P20', 'B1_P21', 'B1_P3', 'B1_P4', 'B1_P5', 'B1_P6',
       'B1_P7', 'B1_P8', 'B1_P9', 'B2_P00', 'B2_P1', 'B2_P10', 'B2_P11',
       'B2_P12', 'B2_P13', 'B2_P14', 'B2_P15', 'B2_P16', 'B2_P17', 'B2_P18',
       'B2_P2', 'B2_P20', 'B2_P3', 'B2_P4', 'B2_P5', 'B2_P6', 'B2_P7', 'B2_P8',
       'B2_P9'],
      dtype='object')

In [31]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer(sparse_output=True)

X_test = test.join(
            pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(test.pop('Product_Holding_B1')),
                index=test.index,
                columns=mlb.classes_).add_prefix('B1_'))

In [32]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df1['Gender'] = label.fit_transform(df1['Gender'])
df1['City_Category'] = label.fit_transform(df1['City_Category'])
df1['Customer_Category'] = label.fit_transform(df1['Customer_Category'])

In [33]:
df1.head()

Customer_ID  Gender  Age  Vintage  Is_Active  City_Category  \
0    CC264719       1   41       14          0              0   
1    CC209679       0   47       14          1              0   
2    CC319633       0   59       14          0              1   
3    CC231413       0   32       16          0              0   
4    CC259633       1   30       15          0              1   

   Customer_Category  B1_P00  B1_P1  B1_P10  ...  B2_P18  B2_P2  B2_P20  \
0                  2       0      0       0  ...       0      0       0   
1                  1       0      0       0  ...       0      0       0   
2                  1       0      0       0  ...       0      0       0   
3                  1       0      0       0  ...       0      0       0   
4                  2       0      0       0  ...       0      0       0   

   B2_P3  B2_P4  B2_P5  B2_P6  B2_P7  B2_P8  B2_P9  
0      0      0      0      0      0      1      0  
1      1      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      1      0      0      0  
4      0      0      0      0      0      1      0  

[5 rows x 49 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
X_test['Gender'] = label.fit_transform(X_test['Gender'])
X_test['City_Category'] = label.fit_transform(X_test['City_Category'])
X_test['Customer_Category'] = label.fit_transform(X_test['Customer_Category'])

In [35]:
df1=df1.iloc[:,1:] #selecting all columns excluding customerid

In [36]:
df1.head()

Gender  Age  Vintage  Is_Active  City_Category  Customer_Category  B1_P00  \
0       1   41       14          0              0                  2       0   
1       0   47       14          1              0                  1       0   
2       0   59       14          0              1                  1       0   
3       0   32       16          0              0                  1       0   
4       1   30       15          0              1                  2       0   

   B1_P1  B1_P10  B1_P11  ...  B2_P18  B2_P2  B2_P20  B2_P3  B2_P4  B2_P5  \
0      0       0       0  ...       0      0       0      0      0      0   
1      0       0       0  ...       0      0       0      1      0      0   
2      0       0       1  ...       0      0       0      0      0      0   
3      0       0       0  ...       0      0       0      0      0      0   
4      0       0       0  ...       0      0       0      0      0      0   

   B2_P6  B2_P7  B2_P8  B2_P9  
0      0      0      1      0  
1      0      0      0      0  
2      0      0      0      0  
3      1      0      0      0  
4      0      0      1      0  

[5 rows x 48 columns]

In [37]:
df1.shape

(37748, 48)

In [38]:
df1.columns

Index(['Gender', 'Age', 'Vintage', 'Is_Active', 'City_Category',
       'Customer_Category', 'B1_P00', 'B1_P1', 'B1_P10', 'B1_P11', 'B1_P12',
       'B1_P13', 'B1_P14', 'B1_P15', 'B1_P16', 'B1_P17', 'B1_P18', 'B1_P19',
       'B1_P2', 'B1_P20', 'B1_P21', 'B1_P3', 'B1_P4', 'B1_P5', 'B1_P6',
       'B1_P7', 'B1_P8', 'B1_P9', 'B2_P00', 'B2_P1', 'B2_P10', 'B2_P11',
       'B2_P12', 'B2_P13', 'B2_P14', 'B2_P15', 'B2_P16', 'B2_P17', 'B2_P18',
       'B2_P2', 'B2_P20', 'B2_P3', 'B2_P4', 'B2_P5', 'B2_P6', 'B2_P7', 'B2_P8',
       'B2_P9'],
      dtype='object')

In [39]:
X_test=X_test.iloc[:,1:] #selecting all columns excluding customerid

In [40]:
y=df1.loc[:,['B2_P00', 'B2_P1', 'B2_P10', 'B2_P11','B2_P12', 'B2_P13', 'B2_P14', 'B2_P15', 'B2_P16', 'B2_P17', 'B2_P18','B2_P2', 'B2_P20', 'B2_P3', 'B2_P4', 'B2_P5', 'B2_P6', 'B2_P7', 'B2_P8','B2_P9']]

In [41]:
y

B2_P00  B2_P1  B2_P10  B2_P11  B2_P12  B2_P13  B2_P14  B2_P15  B2_P16  \
0           0      0       0       0       0       0       0       0       0   
1           0      0       0       0       0       0       0       0       0   
2           1      0       0       0       0       0       0       0       0   
3           0      0       0       0       0       0       0       0       0   
4           0      0       0       0       1       0       0       0       0   
...       ...    ...     ...     ...     ...     ...     ...     ...     ...   
37743       0      0       0       0       0       0       0       0       0   
37744       0      0       0       0       1       0       0       0       0   
37745       0      0       0       0       0       1       0       0       0   
37746       0      1       0       0       0       0       0       0       0   
37747       0      0       0       0       1       0       0       0       0   

       B2_P17  B2_P18  B2_P2  B2_P20  B2_P3  B2_P4  B2_P5  B2_P6  B2_P7  \
0           0       0      0       0      0      0      0      0      0   
1           0       0      0       0      1      0      0      0      0   
2           0       0      0       0      0      0      0      0      0   
3           0       0      0       0      0      0      0      1      0   
4           0       0      0       0      0      0      0      0      0   
...       ...     ...    ...     ...    ...    ...    ...    ...    ...   
37743       0       0      0       0      0      0      0      0      0   
37744       0       0      0       0      0      0      1      0      0   
37745       0       0      0       0      0      0      0      0      0   
37746       0       0      0       0      0      0      0      0      0   
37747       0       0      0       0      0      0      0      0      0   

       B2_P8  B2_P9  
0          1      0  
1          0      0  
2          0      0  
3          0      0  
4          1      0  
...      ...    ...  
37743      0      1  
37744      0      0  
37745      0      0  
37746      0      0  
37747      1      0  

[37748 rows x 20 columns]

In [42]:
X=df1.loc[:,['Gender', 'Age', 'Vintage', 'Is_Active', 'City_Category','Customer_Category', 'B1_P00', 'B1_P1', 'B1_P10', 'B1_P11', 'B1_P12','B1_P13', 'B1_P14', 'B1_P15', 'B1_P16', 'B1_P17', 'B1_P18', 'B1_P19','B1_P2', 'B1_P20', 'B1_P21', 'B1_P3', 'B1_P4', 'B1_P5', 'B1_P6','B1_P7', 'B1_P8', 'B1_P9']]

In [43]:
X

Gender  Age  Vintage  Is_Active  City_Category  Customer_Category  \
0           1   41       14          0              0                  2   
1           0   47       14          1              0                  1   
2           0   59       14          0              1                  1   
3           0   32       16          0              0                  1   
4           1   30       15          0              1                  2   
...       ...  ...      ...        ...            ...                ...   
37743       1   28       24          1              0                  1   
37744       1   36       11          0              1                  1   
37745       1   44       26          1              1                  1   
37746       0   56       15          1              0                  1   
37747       1   29       13          0              1                  1   

       B1_P00  B1_P1  B1_P10  B1_P11  ...  B1_P2  B1_P20  B1_P21  B1_P3  \
0           0      0       0       0  ...      0       0       0      0   
1           0      0       0       0  ...      0       1       0      0   
2           0      0       0       1  ...      0       0       0      0   
3           0      0       0       0  ...      0       0       0      0   
4           0      0       0       0  ...      0       0       1      0   
...       ...    ...     ...     ...  ...    ...     ...     ...    ...   
37743       0      0       0       0  ...      0       0       0      0   
37744       0      0       0       0  ...      0       0       1      0   
37745       0      0       0       0  ...      0       0       0      0   
37746       0      0       0       0  ...      0       0       0      0   
37747       0      0       0       0  ...      0       0       0      0   

       B1_P4  B1_P5  B1_P6  B1_P7  B1_P8  B1_P9  
0          0      0      0      0      0      0  
1          0      0      0      0      0      0  
2          0      0      0      0      0      0  
3          0      0      0      0      1      0  
4          0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...  
37743      0      0      0      0      0      0  
37744      0      0      0      0      0      0  
37745      0      0      0      0      0      0  
37746      0      0      0      0      0      0  
37747      0      0      0      0      0      0  

[37748 rows x 28 columns]

In [44]:
col=['Gender', 'Age', 'Vintage', 'Is_Active', 'City_Category',
       'Customer_Category', 'B1_P00', 'B1_P1', 'B1_P10', 'B1_P11', 'B1_P12',
       'B1_P13', 'B1_P14', 'B1_P15', 'B1_P16', 'B1_P17', 'B1_P18', 'B1_P19',
       'B1_P2', 'B1_P20', 'B1_P21', 'B1_P3', 'B1_P4', 'B1_P5', 'B1_P6',
       'B1_P7', 'B1_P8', 'B1_P9', 'B2_P00', 'B2_P1', 'B2_P10', 'B2_P11',
       'B2_P12', 'B2_P13', 'B2_P14', 'B2_P15', 'B2_P16', 'B2_P17', 'B2_P18',
       'B2_P2', 'B2_P20', 'B2_P3', 'B2_P4', 'B2_P5', 'B2_P6', 'B2_P7', 'B2_P8',
       'B2_P9']

In [45]:
from sklearn.model_selection import train_test_split



# split into train and test
#There is a possibilty that there is a imbalance when we split  train and test ,the either dataset may have bias towards single category
X_train, X_val, y_train, y_val=train_test_split(X, y, test_size=0.25, random_state=10)

In [46]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
classifier = MultiOutputClassifier(KNeighborsClassifier())

In [47]:
classifier.fit(X_train.to_numpy(), y_train.to_numpy())

MultiOutputClassifier(estimator=KNeighborsClassifier())

In [48]:

preds = classifier.predict_proba(X_val.to_numpy())


In [49]:
pred=classifier.predict(X_val.to_numpy())

In [50]:
pred

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
for item in pred:
    print(item)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [52]:
B2_cols=y.columns

In [53]:
B2_cols

Index(['B2_P00', 'B2_P1', 'B2_P10', 'B2_P11', 'B2_P12', 'B2_P13', 'B2_P14',
       'B2_P15', 'B2_P16', 'B2_P17', 'B2_P18', 'B2_P2', 'B2_P20', 'B2_P3',
       'B2_P4', 'B2_P5', 'B2_P6', 'B2_P7', 'B2_P8', 'B2_P9'],
      dtype='object')

In [54]:
from sklearn.metrics import average_precision_score

In [55]:
average_precision_score(y_val.to_numpy(),pred,average='samples')

0.31248896188760544

In [56]:
Final_pred=classifier.predict_proba(X_test.to_numpy())

In [57]:
# creating odd list of K for KNN
mylist = list(range(1,50,2))

In [ ]:
# empty list that will hold accuracy scores
ac_scores = []
ac_scores1 = []


# perform accuracy metrics for values from 1,3,5....19
for k in mylist:
    knn = MultiOutputClassifier(KNeighborsClassifier(n_neighbors=k))
    knn.fit(X_train.to_numpy(), y_train.to_numpy())
    # predict the response
    y_pred = knn.predict(X_val.to_numpy())
    # evaluate accuracy
    scores = accuracy_score(y_val, y_pred)
    ac_scores.append(scores)
    scores1 = average_precision_score(y_val.to_numpy(),pred,average='samples')
    ac_scores1.append(scores1)

# changing to misclassification error
MSE = [1 - x for x in ac_scores]

# determining best k
optimal_k = mylist[MSE.index(min(MSE))]
print("The optimal number of neighbors is %d" % optimal_k)

In [ ]:
preds_cal = []
for item in Final_pred:
    preds_cal.append( [local_item[1] for local_item in item] )

In [ ]:
df_knn = pd.DataFrame(np.array(preds_cal).T, columns=B2_cols)
df_knn.to_csv('knn_preds.csv', index=False)

In [ ]:
pred = pd.read_csv('knn_preds.csv')

In [ ]:
test = pd.concat([test, pred], axis=1)
total_cols = [col for col in test.columns if col.startswith('B2_')]

In [ ]:
total_cols

In [ ]:
pred

In [ ]:
s='B2_P001'
s.split("_")[1]

In [ ]:
def get_labels(row):
    labels = []
    max_val = -1
    max_label = ''
    label_dict = {}
    for col in total_cols:
        if row[col] > max_val:
            max_val = row[col]
            max_label = col.split('_')[-1] 

        if row[col] > 0.5:
            labels.append(col.split('_')[-1])
            label_dict[col.split('_')[-1]] = row[col]
    
    if len(labels) == 0:
        labels.append(max_label)
        
    if len(labels) > 3:
        sorted_dict = dict(sorted(label_dict.items(), key=lambda item: item[1], reverse=True))
        print(sorted_dict)
        labels = []
        labels.extend(list(sorted_dict.keys())[0:3])
        
    return str(labels)

In [ ]:
test['Product_Holding_B2'] = pred.apply(get_labels, axis=1 )

In [ ]:
from ast import literal_eval

sub = pd.read_csv('sample_submission_kF044ur.csv')
sub['Product_Holding_B2']=test['Product_Holding_B2']



In [ ]:
sub

In [ ]:
sub.to_csv("submission1.csv",index=False)